version: 2.1
executors:
  # The api environment uses Testcontainers, thats why we need a machine executor
  machine-ubuntu-executor:
    machine: 
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"
  docker-node-executor:
    docker:
      - image: cimg/node:current

jobs:
  api:
    executor: machine-ubuntu-executor
    steps:
      - checkout
      - restore_cache:
          keys: 
            - gradle-cache-{{ checksum "./api/build.gradle" }}
      - run: |
          cd api
          ./gradlew build
      - save_cache:
          name: Save gradle cache to cache
          paths:
            - ~/.gradle/caches/
            - ./api/.gradle
          key: gradle-cache-{{ checksum "./api/build.gradle" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - run: |
          cd api
          docker build -t mlhmz/family-task-tracking:${CIRCLE_BRANCH//[\/]/_} .
      - run:
          name: Push image
          command: |
            docker login -u ${DHU} -p ${DHP}
            docker push mlhmz/family-task-tracking:${CIRCLE_BRANCH//[\/]/_}

  frontend:
    executor: docker-node-executor
    steps:
      - checkout
      - run: |
          cd frontend
          npm ci
          npm run lint
      - run: |
          cd frontend
          docker build -t mlhmz/family-task-tracking-frontend:${CIRCLE_BRANCH//[\/]/_} .
      - run:
          name: Push image
          command: |
            docker login -u ${DHU} -p ${DHP}
            docker push mlhmz/family-task-tracking-frontend:${CIRCLE_BRANCH//[\/]/_}


workflows:
  build-workflow:
    jobs:
      - api
      - frontend
